create table "public"."mailings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "subject" text not null,
    "to" text[] not null,
    "body" text not null,
    "event_id" uuid not null
);


alter table "public"."mailings" enable row level security;

alter table "public"."favourites" add column "user_details" uuid;

alter table "public"."user_details" add column "email" text not null default ''::text;

CREATE UNIQUE INDEX mailings_pkey ON public.mailings USING btree (id);

alter table "public"."mailings" add constraint "mailings_pkey" PRIMARY KEY using index "mailings_pkey";

alter table "public"."favourites" add constraint "favourites_user_details_fkey" FOREIGN KEY (user_details) REFERENCES user_details(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."favourites" validate constraint "favourites_user_details_fkey";

alter table "public"."mailings" add constraint "mailings_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."mailings" validate constraint "mailings_event_id_fkey";

grant delete on table "public"."mailings" to "anon";

grant insert on table "public"."mailings" to "anon";

grant references on table "public"."mailings" to "anon";

grant select on table "public"."mailings" to "anon";

grant trigger on table "public"."mailings" to "anon";

grant truncate on table "public"."mailings" to "anon";

grant update on table "public"."mailings" to "anon";

grant delete on table "public"."mailings" to "authenticated";

grant insert on table "public"."mailings" to "authenticated";

grant references on table "public"."mailings" to "authenticated";

grant select on table "public"."mailings" to "authenticated";

grant trigger on table "public"."mailings" to "authenticated";

grant truncate on table "public"."mailings" to "authenticated";

grant update on table "public"."mailings" to "authenticated";

grant delete on table "public"."mailings" to "service_role";

grant insert on table "public"."mailings" to "service_role";

grant references on table "public"."mailings" to "service_role";

grant select on table "public"."mailings" to "service_role";

grant trigger on table "public"."mailings" to "service_role";

grant truncate on table "public"."mailings" to "service_role";

grant update on table "public"."mailings" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."mailings"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for authenticated users"
on "public"."mailings"
as permissive
for select
to authenticated
using (true);



